# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

  #   name: Frontend tests
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '17.1'
  #         cache: 'npm'
  #         cache-dependency-path: app/package-lock.json
  #     - name: Tests
  #       run: |
  #         npm ci
  #         npm run test
  #       working-directory: app
  # prettier:

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  frontend-test:
    name: Frontend tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.1'
          cache: 'npm'
          cache-dependency-path: my-app/package-lock.json
      - name: Tests
        run: |
          npm ci
          npm run test
        working-directory: my-app
    
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        run: npx prettier --check
        working-directory: my-app
